export const VALIDATE_EMAIL_REQUEST = "VALIDATE_EMAIL_REQUEST"
export const VALIDATE_EMAIL_SUCCESS = "VALIDATE_EMAIL_SUCCESS"
export const VALIDATE_EMAIL_FAIL = "VALIDATE_EMAIL_FAIL"
export const VALIDATE_EMAIL_RESET = "VALIDATE_EMAIL_RESET"

export const REGISTER_REQUEST = "REGISTER_REQUEST"
export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const REGISTER_FAIL = "REGISTER_FAIL"

export const LOGIN_REQUEST = "LOGIN_REQUEST"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAIL = "LOGIN_FAIL"
export const LOGOUT = "LOGOUT"